### ISSUE TITLE
Launching server with newest version 1.18.2-4.8.1 crashes due to index out of bounds -error

### ISSUE THREAD

**Issue by Stimraug** [Andromander/Nifty#37]
[latest.log](https://github.com/Andromander/Ornamental/files/9029145/latest.log)

[01Jul2022 16:19:38.914] [Server thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: Index 9 out of bounds for length 9
	Index: 4
	Listeners:
		0: NORMAL
		1: net.minecraftforge.eventbus.EventBus$$Lambda$3003/0x00000008014886a0@4a7fb515
		2: ASM: class com.ldtteam.domumornamentum.event.handlers.ForgeBusEventHandler onServerStarted(Lnet/minecraftforge/event/server/ServerStartedEvent;)V
		3: ASM: class com.ldtteam.structurize.event.EventSubscriber onServerStarted(Lnet/minecraftforge/event/server/ServerStartedEvent;)V
		4: ASM: class com.minecolonies.coremod.event.TagWorkAroundEventHandler$TagFMLEventHandlers onServerStarted(Lnet/minecraftforge/event/server/ServerStartedEvent;)V
		5: net.minecraftforge.eventbus.EventBus$$Lambda$3003/0x00000008014886a0@56b13190
java.lang.ArrayIndexOutOfBoundsException: Index 9 out of bounds for length 9
	at TRANSFORMER/ornamental@4.8.1/com.androsa.ornamental.items.OrnamentBlockItem.getBurnTime(OrnamentBlockItem.java:47)
	at TRANSFORMER/forge@40.0.45/net.minecraftforge.common.extensions.IForgeItemStack.getBurnTime(IForgeItemStack.java:77)
	at TRANSFORMER/forge@40.0.45/net.minecraftforge.common.ForgeHooks.getBurnTime(ForgeHooks.java:1183)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.block.entity.AbstractFurnaceBlockEntity.m_58399_(AbstractFurnaceBlockEntity.java:352)
	at TRANSFORMER/minecolonies@1.18.2-1.0.612-ALPHA/com.minecolonies.api.compatibility.CompatibilityManager.discoverFuel(CompatibilityManager.java:580)
	at TRANSFORMER/minecolonies@1.18.2-1.0.612-ALPHA/com.minecolonies.api.compatibility.CompatibilityManager.discover(CompatibilityManager.java:202)
	at TRANSFORMER/minecolonies@1.18.2-1.0.612-ALPHA/com.minecolonies.coremod.event.TagWorkAroundEventHandler.loadRecipes(TagWorkAroundEventHandler.java:55)
	at TRANSFORMER/minecolonies@1.18.2-1.0.612-ALPHA/com.minecolonies.coremod.event.TagWorkAroundEventHandler$TagFMLEventHandlers.onServerStarted(TagWorkAroundEventHandler.java:174)
	at net.minecraftforge.eventbus.ASMEventHandler_118_TagFMLEventHandlers_onServerStarted_ServerStartedEvent.invoke(.dynamic)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at TRANSFORMER/forge@40.0.45/net.minecraftforge.server.ServerLifecycleHooks.handleServerStarted(ServerLifecycleHooks.java:99)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:662)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261)
	at java.base/java.lang.Thread.run(Thread.java:833)

Thanks for the mod, I hope this is something that you can fix and not some other problem. :)

**Comment by Andromander** [comment]
Fix should now be in version 4.8.2.

**Comment by Stimraug** [comment]
Thank you!!
