### ISSUE TITLE
[1.19.3 - 4.10.39] NoClassDefFoundError, fatal crash

### ISSUE THREAD

**Issue by ZiotecH** [Andromander/Nifty#41]
Trying the latest build (4.10.39) fails to initialise, leading to a fatal crash.

### Environment

- Minecraft 1.19.3
- Forge 44.1.16
- Windows 11
- Java 17.0.5 (Oracle)

### Crash Report
```
-- MOD ornamental --
Details:
	Caused by 0: java.lang.reflect.InvocationTargetException
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.3-44.1.16.jar%23303!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.3-44.1.16.jar%23302!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}
 
	Caused by 1: java.lang.NoClassDefFoundError: org/apache/commons/compress/utils/Lists
		at com.androsa.ornamental.data.OrnamentalBlockTags.<clinit>(OrnamentalBlockTags.java:20) ~[ornamental-1.19.3-4.10.39.jar%23273!/:1.19.3-4.10.39] {re:classloading}
		at com.androsa.ornamental.builder.OrnamentBuilders.<clinit>(OrnamentBuilders.java:26) ~[ornamental-1.19.3-4.10.39.jar%23273!/:1.19.3-4.10.39] {re:classloading}
		at com.androsa.ornamental.registry.ModBlocks.<clinit>(ModBlocks.java:23) ~[ornamental-1.19.3-4.10.39.jar%23273!/:1.19.3-4.10.39] {re:classloading}
		at com.androsa.ornamental.OrnamentalMod.<init>(OrnamentalMod.java:32) ~[ornamental-1.19.3-4.10.39.jar%23273!/:1.19.3-4.10.39] {re:classloading}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.3-44.1.16.jar%23303!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.3-44.1.16.jar%23302!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}
 
	Mod File: /[redacted]/mods/ornamental-1.19.3-4.10.39.jar
	Failure message: Ornamental (ornamental) has failed to load correctly
		java.lang.reflect.InvocationTargetException: null
	Mod Version: 1.19.3-4.10.39
	Mod Issue URL: https://github.com/Andromander/Ornamental/issues
	Exception message: java.lang.ClassNotFoundException: org.apache.commons.compress.utils.Lists
Stacktrace:
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-2.1.6.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-2.1.6.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at com.androsa.ornamental.data.OrnamentalBlockTags.<clinit>(OrnamentalBlockTags.java:20) ~[ornamental-1.19.3-4.10.39.jar%23273!/:1.19.3-4.10.39] {re:classloading}
	at com.androsa.ornamental.builder.OrnamentBuilders.<clinit>(OrnamentBuilders.java:26) ~[ornamental-1.19.3-4.10.39.jar%23273!/:1.19.3-4.10.39] {re:classloading}
	at com.androsa.ornamental.registry.ModBlocks.<clinit>(ModBlocks.java:23) ~[ornamental-1.19.3-4.10.39.jar%23273!/:1.19.3-4.10.39] {re:classloading}
	at com.androsa.ornamental.OrnamentalMod.<init>(OrnamentalMod.java:32) ~[ornamental-1.19.3-4.10.39.jar%23273!/:1.19.3-4.10.39] {re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.3-44.1.16.jar%23303!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.3-44.1.16.jar%23302!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}
```

**Comment by Andromander** [comment]
Can I get you to try [this build](https://tamaized.com/artifacts/builds/Andromander/Ornamental/40/ornamental-1.19.3-4.10.40.jar)?

**Comment by ZiotecH** [comment]
That build does seem to have fixed the issue, cheers!

**Comment by Andromander** [comment]
All I needed to know. I'll get this (and the addons) a new build in a moment.
